# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "generic/debian9"
  config.vm.box_version = "3.0.6"

  config.vm.network "private_network", ip: "192.168.33.201"
  config.ssh.insert_key = false
  config.vm.provision :shell, :path => "bootstrap.sh"
  config.vm.synced_folder '.', '/vagrant', disabled: true

end
