# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(2) do |config|

  config.vm.define :default do |host|
    host.vm.box = "centos-7.2-x86_64"
    host.vm.network :private_network, ip: "192.168.33.101"
    host.ssh.insert_key = false
    host.vm.provision :shell, :path => "bootstrap.sh"
  end
end
