# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(2) do |config|

  config.vm.define :vbox do |host|
    host.vm.box = "centos/7"
    host.vm.network :private_network, ip: "192.168.33.201"
    host.ssh.insert_key = false
  end

end
