# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.box_url = "https://vagrantcloud.com/ubuntu/xenial64"
  config.vm.box_version = "20181122.1.0"

  config.vm.network "private_network", ip: "192.168.33.201"
  config.ssh.insert_key = false
  config.vm.provision :shell, :path => "bootstrap.sh"
  config.vm.synced_folder '.', '/vagrant', disabled: true

end
